/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mediatheque1;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Emprenter_doc extends javax.swing.JFrame {
    static String groupe;

        Connection con= null;
    PreparedStatement pst= null;
    PreparedStatement ps= null;
    ResultSet rs= null;
   
     public Emprenter_doc(String groupe) {
         this.groupe=groupe;
        initComponents();
        clock();
        con = Connectionbdd.ConnecrDb();
    }
void fermer(){dispose();}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bDate = new javax.swing.JLabel();
        bTime = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CodeEmprunt3 = new javax.swing.JTextField();
        ModifierButton = new javax.swing.JButton();
        EnvoyerEm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CodeEmprunt = new javax.swing.JTextField();
        CodeLecteur = new javax.swing.JTextField();
        CodeDocument = new javax.swing.JTextField();
        Date_Empr = new javax.swing.JTextField();
        Date_Retour = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        RetournerRel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CodeEmprunt1 = new javax.swing.JTextField();
        CodeLecteur1 = new javax.swing.JTextField();
        CodeDoc1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        EnvoyerEmail = new javax.swing.JPanel();
        ToField = new javax.swing.JTextField();
        FromField = new javax.swing.JTextField();
        SubjectField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageFiled = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 125, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 50));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel4.setText("MYS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 60));

        bDate.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bDate.setText("Date");
        jPanel1.add(bDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 190, 30));

        bTime.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bTime.setText("Time");
        jPanel1.add(bTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 200, -1));

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 153));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        jButton9.setText("Retour");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Regler Cotisation");

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Code Lecteur :");

        ModifierButton.setBackground(new java.awt.Color(0, 102, 102));
        ModifierButton.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        ModifierButton.setForeground(new java.awt.Color(255, 255, 255));
        ModifierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        ModifierButton.setText("Valider");
        ModifierButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        ModifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(788, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CodeEmprunt3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(ModifierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodeEmprunt3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(ModifierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Régler Cotisation", jPanel2);

        EnvoyerEm.setBackground(new java.awt.Color(0, 153, 153));
        EnvoyerEm.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                EnvoyerEmComponentAdded(evt);
            }
        });
        EnvoyerEm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Code Emprunt :");
        EnvoyerEm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 96, 140, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Code  Lecteur :");
        EnvoyerEm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 160, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Code document :");
        EnvoyerEm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date d'emprunt :");
        EnvoyerEm.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date de retour :");
        EnvoyerEm.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));
        EnvoyerEm.add(CodeEmprunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 260, 30));
        EnvoyerEm.add(CodeLecteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 172, 260, 30));
        EnvoyerEm.add(CodeDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 242, 260, 30));

        Date_Empr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_EmprActionPerformed(evt);
            }
        });
        EnvoyerEm.add(Date_Empr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 260, 30));

        Date_Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_RetourActionPerformed(evt);
            }
        });
        EnvoyerEm.add(Date_Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 260, 30));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add2.png"))); // NOI18N
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        EnvoyerEm.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 230, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empr.png"))); // NOI18N
        EnvoyerEm.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 26, 170, 110));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        EnvoyerEm.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 170, 50));

        jLabel7.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ajouter Emprunt");
        EnvoyerEm.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 26, 350, 40));

        jTabbedPane1.addTab("Ajouter Emprunt", EnvoyerEm);

        RetournerRel.setBackground(new java.awt.Color(0, 153, 153));
        RetournerRel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Sitka Heading", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Retourner Emprunt");
        RetournerRel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 430, 60));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Code Emprunt :");
        RetournerRel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 140, 30));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Code  Lecteur :");
        RetournerRel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 160, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Code document :");
        RetournerRel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        CodeEmprunt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeEmprunt1ActionPerformed(evt);
            }
        });
        RetournerRel.add(CodeEmprunt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 260, 30));
        RetournerRel.add(CodeLecteur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 260, 30));
        RetournerRel.add(CodeDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 260, 30));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/retourner.png"))); // NOI18N
        jButton3.setText("Retourner");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        RetournerRel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 230, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EM.png"))); // NOI18N
        RetournerRel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 26, 170, 110));

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        jButton7.setText("Retour");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        RetournerRel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 170, 50));

        jTabbedPane1.addTab("Retourner Emprunt", RetournerRel);

        EnvoyerEmail.setBackground(new java.awt.Color(0, 102, 102));
        EnvoyerEmail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToFieldActionPerformed(evt);
            }
        });
        EnvoyerEmail.add(ToField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 280, 30));

        FromField.setText("mysmouna371@gmail.com");
        FromField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromFieldActionPerformed(evt);
            }
        });
        EnvoyerEmail.add(FromField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 280, 30));
        EnvoyerEmail.add(SubjectField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 280, 30));

        MessageFiled.setColumns(20);
        MessageFiled.setRows(5);
        jScrollPane1.setViewportView(MessageFiled);

        EnvoyerEmail.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 280, 100));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("To:");
        EnvoyerEmail.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 120, 30));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("From:");
        EnvoyerEmail.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 140, -1));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Message :");
        EnvoyerEmail.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 130, -1));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Subject:");
        EnvoyerEmail.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/send.png"))); // NOI18N
        jButton5.setText("Envoyer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        EnvoyerEmail.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 230, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/em2.png"))); // NOI18N
        EnvoyerEmail.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 260, 150));

        jButton8.setBackground(new java.awt.Color(0, 102, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        jButton8.setText("Retour");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        EnvoyerEmail.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 170, 50));

        jTabbedPane1.addTab("Relance", EnvoyerEmail);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 970, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnvoyerEmComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_EnvoyerEmComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_EnvoyerEmComponentAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
           String sql = "INSERT INTO `emprunt`(`idEmprunt`, `idPersonne`, `cote`, `dateEmprunt`, `dateRetour`, `docRetournee`)values(?,?,?,?,?,0)";
            String sql2 = "UPDATE documents SET etat = 'NON_DISPONIBLE' where cote=?";
            pst = con.prepareStatement(sql);
            ps = con.prepareStatement(sql2);
           
           ps.setString(1,CodeDoc1.getText());
           
           
           
           
           pst = con.prepareStatement(sql);
           pst.setString(1,CodeEmprunt.getText());
           pst.setString(2,CodeLecteur.getText());
           pst.setString(3,CodeDocument.getText());
           pst.setString(4,Date_Empr.getText());
           pst.setString(5,Date_Retour.getText());
           pst.executeUpdate(); ps.executeUpdate();
           con.close();
           JOptionPane.showMessageDialog(null,"enregistrement reussi");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Date_EmprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_EmprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_EmprActionPerformed

    private void Date_RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_RetourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_RetourActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          try{
            String sql = "UPDATE emprunt SET docRetournee= 1 where idEmprunt=? and idPersonne=? and cote=?  ";
            String sql2 = "UPDATE documents SET etat = 'DISPONIBLE' where cote=?";
            pst = con.prepareStatement(sql);
            ps = con.prepareStatement(sql2);
           pst.setString(1,CodeEmprunt1.getText());
           pst.setString(2,CodeLecteur1.getText());
           pst.setString(3,CodeDoc1.getText());
           ps.setString(1,CodeDoc1.getText());
           pst.executeUpdate();
           ps.executeUpdate();
           con.close();
           JOptionPane.showMessageDialog(null,"retournemenT valide");}
          catch(Exception e){
             e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CodeEmprunt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeEmprunt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeEmprunt1ActionPerformed

    private void ToFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToFieldActionPerformed

    private void FromFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromFieldActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         try{ String ToEmail=ToField.getText();
        String FromEmail=FromField.getText();//mysmouna371@gmail.com
        String Subject=SubjectField.getText();
        String FormEmailPassword ="tcojjafjqzjcizoq";
        
        Properties pr=new Properties();
        pr.put("mail.smtp.auth", "true");
        pr.put("mail.smtp.starttls.enable","true");
        pr.put("mail.smtp.host", "smtp.gmail.com");
        pr.put("mail.smtp.port", "587");
        
        Session sc= Session.getDefaultInstance(pr,new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication(){
            return new PasswordAuthentication(FromEmail,FormEmailPassword);}
        });
        
        
        MimeMessage message=new MimeMessage(sc);
        message.setFrom(new InternetAddress(FromEmail));
        message.addRecipient(Message.RecipientType.TO,new InternetAddress(ToEmail));
        message.setSubject(Subject);
        message.setContent(MessageFiled.getText(),"text/plain");
        message.setSentDate(new Date());
        Transport.send(message);
         JOptionPane.showMessageDialog(null,"sent");
                }catch(Exception e ){System.out.println(""+e);}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        if(groupe.equals("B")){
                          Bénevole benevole = new Bénevole(groupe);
                          benevole.setVisible(true);
                          fermer();
                          
                    }
                    else if(groupe.equals("P")){
                          Personnel per = new Personnel(groupe);
                          per.setVisible(true);
                    fermer();}
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       if(groupe.equals("B")){
                          Bénevole benevole = new Bénevole(groupe);
                          benevole.setVisible(true);
                          fermer();
                          
                    }
                    else if(groupe.equals("P")){
                          Personnel per = new Personnel(groupe);
                          per.setVisible(true);
                    fermer();}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        if(groupe.equals("B")){
                          Bénevole benevole = new Bénevole(groupe);
                          benevole.setVisible(true);
                          fermer();
                          
                    }
                    else if(groupe.equals("P")){
                          Personnel per = new Personnel(groupe);
                          per.setVisible(true);
                    fermer();}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
          if(groupe.equals("B")){
                          Bénevole benevole = new Bénevole(groupe);
                          benevole.setVisible(true);
                          fermer();
                          
                    }
                    else if(groupe.equals("P")){
                          Personnel per = new Personnel(groupe);
                          per.setVisible(true);
                    fermer();}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ModifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierButtonActionPerformed
      try{
            String sql = "UPDATE personne SET cotisation= 1 where idPersonne=? ";

           pst = con.prepareStatement(sql);
           pst.setString(1,CodeEmprunt3.getText());
           pst.executeUpdate();
           con.close();
           JOptionPane.showMessageDialog(null,"reglement valide");}
          catch(Exception e){
             e.printStackTrace();
        }       
    }//GEN-LAST:event_ModifierButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emprenter_doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emprenter_doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emprenter_doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emprenter_doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emprenter_doc(groupe).setVisible(true);
            }
        });
    }
public void clock(){
        {
            Thread clock=new Thread(){
            public void run(){
            try{
            while(true)
            {Calendar cal= new GregorianCalendar();
            int day=cal.get(Calendar.DAY_OF_MONTH);
            int month=cal.get(Calendar.MONTH)+1;
            int year=cal.get(Calendar.YEAR);
            
            int second=cal.get(Calendar.SECOND);
            int minute =cal.get(Calendar.MINUTE);
            int hour =cal.get(Calendar.HOUR);
            
            bTime.setText(hour+":"+minute+":"+second);
            bDate.setText(year+"-"+month+"-"+day);
                 sleep(1000);
                    
            }}
            catch(Exception e){JOptionPane.showMessageDialog(rootPane,e);}}
        };
        clock.start();}}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodeDoc1;
    private javax.swing.JTextField CodeDocument;
    private javax.swing.JTextField CodeEmprunt;
    private javax.swing.JTextField CodeEmprunt1;
    private javax.swing.JTextField CodeEmprunt3;
    private javax.swing.JTextField CodeLecteur;
    private javax.swing.JTextField CodeLecteur1;
    private javax.swing.JTextField Date_Empr;
    private javax.swing.JTextField Date_Retour;
    private javax.swing.JPanel EnvoyerEm;
    private javax.swing.JPanel EnvoyerEmail;
    private javax.swing.JTextField FromField;
    private javax.swing.JTextArea MessageFiled;
    private javax.swing.JButton ModifierButton;
    private javax.swing.JPanel RetournerRel;
    private javax.swing.JTextField SubjectField;
    private javax.swing.JTextField ToField;
    private javax.swing.JLabel bDate;
    private javax.swing.JLabel bTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
