/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mediatheque1;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class gestion_acha extends javax.swing.JFrame {
    Connection con= null;
    PreparedStatement pst= null;
    ResultSet rs= null;
    DefaultTableModel model;
    public gestion_acha() {
        initComponents();
        clock();
        con = Connectionbdd.ConnecrDb();
        tablelord();
    }
 public void fermer(){dispose();}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bDate = new javax.swing.JLabel();
        bTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        IdAchat_text = new javax.swing.JTextField();
        IdLecteur_text = new javax.swing.JTextField();
        IdDocument_text1 = new javax.swing.JTextField();
        DateAchat_text = new javax.swing.JTextField();
        PrixAchat_text = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableDoc = new javax.swing.JTable();
        retourbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 50));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel4.setText("MYS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 60));

        bDate.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bDate.setText("Date");
        jPanel1.add(bDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 190, 30));

        bTime.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bTime.setText("Time");
        jPanel1.add(bTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 200, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 56, 940, 260));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id Achat :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 86, 100, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Id Lecteur :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 155, 120, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Id Document :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 230, 140, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date Achat :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 85, 180, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Prix Achat :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 145, 140, 50));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add2.png"))); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 223, 250, 60));

        IdAchat_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdAchat_textActionPerformed(evt);
            }
        });
        jPanel1.add(IdAchat_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 92, 250, 30));
        jPanel1.add(IdLecteur_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 162, 250, 30));
        jPanel1.add(IdDocument_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 232, 240, 30));
        jPanel1.add(DateAchat_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 92, 230, 30));
        jPanel1.add(PrixAchat_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 162, 230, 30));

        TableDoc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TableDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cote", "titre", "auteur", "date", "domicile", "etat", "emplacement", "prix", "caution", "type"
            }
        ));
        TableDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDocMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableDoc);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 930, 230));

        retourbutton.setBackground(new java.awt.Color(0, 102, 102));
        retourbutton.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        retourbutton.setForeground(new java.awt.Color(255, 255, 255));
        retourbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        retourbutton.setText("Retour");
        retourbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        retourbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(retourbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TableDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDocMouseClicked
        DefaultTableModel model=(DefaultTableModel )TableDoc.getModel();
        int selectrowindex =TableDoc.getSelectedRow();
        IdAchat_text.setText(model.getValueAt(selectrowindex,0).toString());
        IdLecteur_text.setText(model.getValueAt(selectrowindex,1).toString());
        IdDocument_text1.setText(model.getValueAt(selectrowindex,2).toString());
        DateAchat_text.setText(model.getValueAt(selectrowindex,3).toString());
        PrixAchat_text.setText(model.getValueAt(selectrowindex,4).toString());
        
       
    }//GEN-LAST:event_TableDocMouseClicked

    private void retourbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourbuttonActionPerformed
       Personnel p = new Personnel();
        p.setVisible(true);
        fermer();
    }//GEN-LAST:event_retourbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try{
           String sql = "insert into achat (idAchat,idPersonne,cote,dateAchat,prixAchat)values(?,?,?,?,?)";
           pst = con.prepareStatement(sql);
           pst.setString(1,IdAchat_text.getText());
           pst.setString(2,IdLecteur_text.getText());
           pst.setString(3,IdDocument_text1.getText());
           pst.setString(4,DateAchat_text.getText());
           pst.setString(5,PrixAchat_text.getText());
           pst.executeUpdate();
           clearFiled();tablelord();
           con.close();
           JOptionPane.showMessageDialog(null,"enregistrement reussi"); 
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IdAchat_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdAchat_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdAchat_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestion_acha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestion_acha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestion_acha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestion_acha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestion_acha().setVisible(true);
            }
        });
    }
    
     public void tablelord(){
          
    try{
    String sql="SELECT * FROM `achat` ";
    pst=con.prepareStatement(sql);
    rs=pst.executeQuery();
    
   
    TableDoc.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
    }
       catch(Exception e){JOptionPane.showConfirmDialog(rootPane, e);}}
public void clock(){
        {
            Thread clock=new Thread(){
            public void run(){
            try{
            while(true)
            {Calendar cal= new GregorianCalendar();
            int day=cal.get(Calendar.DAY_OF_MONTH);
            int month=cal.get(Calendar.MONTH)+1;
            int year=cal.get(Calendar.YEAR);
            
            int second=cal.get(Calendar.SECOND);
            int minute =cal.get(Calendar.MINUTE);
            int hour =cal.get(Calendar.HOUR);
            
            bTime.setText(hour+":"+minute+":"+second);
            bDate.setText(year+"-"+month+"-"+day);
                 sleep(1000);
                    
            }}
            catch(Exception e){JOptionPane.showMessageDialog(rootPane,e);}}
        };
        clock.start();}}
    private void clearFiled(){
    IdAchat_text.setText(""); 
    IdLecteur_text.setText(""); 
   IdDocument_text1.setText("");    
   DateAchat_text.setText(""); 
    IdDocument_text1.setText(""); 
    PrixAchat_text.setText(""); 
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateAchat_text;
    private javax.swing.JTextField IdAchat_text;
    private javax.swing.JTextField IdDocument_text1;
    private javax.swing.JTextField IdLecteur_text;
    private javax.swing.JTextField PrixAchat_text;
    private javax.swing.JTable TableDoc;
    private javax.swing.JLabel bDate;
    private javax.swing.JLabel bTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton retourbutton;
    // End of variables declaration//GEN-END:variables
}
