/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mediatheque1;

import static java.lang.Thread.sleep;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author PC
 */
public class Gestion_benevole extends javax.swing.JFrame {

     Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public Gestion_benevole() {
        initComponents();
         clock();
        conn=Connectionbdd.ConnecrDb();
        autoId();
        tablelord();
    }
public void fermer(){dispose();}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bDate = new javax.swing.JLabel();
        bTime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IdLabel = new javax.swing.JLabel();
        NomLabel = new javax.swing.JLabel();
        PrenomLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        DateEntreeLabel = new javax.swing.JLabel();
        DateSortieLabel = new javax.swing.JLabel();
        DateInsLabel = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        NomField = new javax.swing.JTextField();
        PrenomFieled = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        dateentreeField = new javax.swing.JTextField();
        datesortieField = new javax.swing.JTextField();
        dateinscField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AjouterButton = new javax.swing.JButton();
        ModifierButton = new javax.swing.JButton();
        SupprimerButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableDoc = new javax.swing.JTable();
        retourbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Bénevole");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 630));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 950, 60));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel4.setText("MYS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 60));

        bDate.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bDate.setText("Date");
        jPanel1.add(bDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 190, 30));

        bTime.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bTime.setText("Time");
        jPanel1.add(bTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 200, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 56, 950, 260));

        IdLabel.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        IdLabel.setForeground(new java.awt.Color(255, 255, 255));
        IdLabel.setText("ID:");
        jPanel1.add(IdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 66, 60, 30));

        NomLabel.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        NomLabel.setForeground(new java.awt.Color(255, 255, 255));
        NomLabel.setText("NOM:");
        jPanel1.add(NomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 106, 70, 40));

        PrenomLabel.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        PrenomLabel.setForeground(new java.awt.Color(255, 255, 255));
        PrenomLabel.setText("Prenom:");
        jPanel1.add(PrenomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 150, 80, 40));

        DateLabel.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateLabel.setText("Date Naiss :");
        jPanel1.add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 200, 90, 40));

        EmailLabel.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("Email:");
        jPanel1.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 250, 80, 40));

        PasswordLabel.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Password:");
        jPanel1.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 96, 100, 30));

        DateEntreeLabel.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        DateEntreeLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateEntreeLabel.setText("Date entree:");
        jPanel1.add(DateEntreeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 136, 100, 40));

        DateSortieLabel.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        DateSortieLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateSortieLabel.setText("Date sortie:");
        jPanel1.add(DateSortieLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 190, 90, 30));

        DateInsLabel.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        DateInsLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateInsLabel.setText("Date inscrip:");
        jPanel1.add(DateInsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 236, 90, 40));

        IdField.setEditable(false);
        jPanel1.add(IdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 62, 170, 30));
        jPanel1.add(NomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 102, 170, 30));
        jPanel1.add(PrenomFieled, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 170, 30));
        jPanel1.add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 202, 160, 30));
        jPanel1.add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 252, 160, 30));

        jPasswordField1.setText("jPasswordField1");
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 94, 160, 30));
        jPanel1.add(dateentreeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 142, 160, 30));
        jPanel1.add(datesortieField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 192, 160, 30));
        jPanel1.add(dateinscField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 242, 160, 30));

        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 76, 300, 220));

        AjouterButton.setBackground(new java.awt.Color(0, 102, 102));
        AjouterButton.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        AjouterButton.setForeground(new java.awt.Color(255, 255, 255));
        AjouterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add2.png"))); // NOI18N
        AjouterButton.setText("Ajouter");
        AjouterButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        AjouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AjouterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 93, 210, 50));

        ModifierButton.setBackground(new java.awt.Color(0, 102, 102));
        ModifierButton.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        ModifierButton.setForeground(new java.awt.Color(255, 255, 255));
        ModifierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        ModifierButton.setText("Modifier");
        ModifierButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        ModifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ModifierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 160, 210, 50));

        SupprimerButton.setBackground(new java.awt.Color(0, 102, 102));
        SupprimerButton.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        SupprimerButton.setForeground(new java.awt.Color(255, 255, 255));
        SupprimerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        SupprimerButton.setText("Supprimer");
        SupprimerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        SupprimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SupprimerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 230, 210, 50));

        TableDoc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TableDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cote", "titre", "auteur", "date", "domicile", "etat", "emplacement", "prix", "caution", "type"
            }
        ));
        TableDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDocMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableDoc);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 930, 230));

        retourbutton.setBackground(new java.awt.Color(0, 102, 102));
        retourbutton.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        retourbutton.setForeground(new java.awt.Color(255, 255, 255));
        retourbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        retourbutton.setText("Retour");
        retourbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        retourbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(retourbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 560, 220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterButtonActionPerformed
        autoId();
        String nom=NomField.getText();
        String prenom=PrenomFieled.getText();
        String date=dateTextField.getText();
        String password=jPasswordField1.getText();
        String email=EmailField.getText();
        String dateent=dateentreeField.getText();
        String datesort=datesortieField.getText();
        String dateinsc=dateinscField.getText();

        try {
            String sql="INSERT INTO `personne`( `nom`, `prenom`, `dateNaissance`, `email`, `password`, `dateEntree`, `dateSortie`, `dateInscription`, `cotisation`, `nbrEmprunt`,`groupe`) VALUES ('"+nom+"','"+prenom+"','"+date+"','"+email+"','"+password+"','"+dateent+"','"+datesort+"','"+dateinsc+"','1','0','B')";

            PreparedStatement pst=(PreparedStatement)conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Successfully insert");
        }catch(Exception e  ){
            JOptionPane.showMessageDialog(rootPane,e);

        }
        clearFiled();tablelord();
    }//GEN-LAST:event_AjouterButtonActionPerformed

    private void ModifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierButtonActionPerformed
        String id=IdField.getText();
        String nom=NomField.getText();
        String prenom=PrenomFieled.getText();
        String date=dateTextField.getText();
        String password=jPasswordField1.getText();
        String email=EmailField.getText();
        String dateent=dateentreeField.getText();
        String datesort=datesortieField.getText();
        String dateinsc=dateinscField.getText();

        try{
            String sql="UPDATE `personne` SET `nom`='"+nom+"',`prenom`='"+prenom+"',`dateNaissance`='"+date+"',`password`='"+password+"',`dateEntree`='"+dateent+"',`dateSortie`='"+datesort+"',`dateInscription`='"+dateinsc+"' WHERE `idPersonne`='"+id+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Update success");
            tablelord();
        }catch(Exception e ){JOptionPane.showMessageDialog(rootPane, e);}
    }//GEN-LAST:event_ModifierButtonActionPerformed

    private void SupprimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerButtonActionPerformed
        try{
            String sql="DELETE FROM `personne` WHERE `idPersonne`='"+IdField.getText()+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Delete success");
            tablelord();
        }
        catch(Exception e) {JOptionPane.showMessageDialog(rootPane, e);}
    }//GEN-LAST:event_SupprimerButtonActionPerformed

    private void TableDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDocMouseClicked
        DefaultTableModel model=(DefaultTableModel )TableDoc.getModel();
        int selectrowindex =TableDoc.getSelectedRow();
        IdField.setText(model.getValueAt(selectrowindex,0).toString());
        NomField.setText(model.getValueAt(selectrowindex,1).toString());
        PrenomFieled.setText(model.getValueAt(selectrowindex,2).toString());
        dateTextField.setText(model.getValueAt(selectrowindex,3).toString());
        EmailField.setText(model.getValueAt(selectrowindex,4).toString());
        jPasswordField1.setText(model.getValueAt(selectrowindex,5).toString());

        dateentreeField.setText(model.getValueAt(selectrowindex,6).toString());
        datesortieField.setText(model.getValueAt(selectrowindex,7).toString());
        dateinscField.setText(model.getValueAt(selectrowindex,8).toString());

    }//GEN-LAST:event_TableDocMouseClicked

    private void retourbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourbuttonActionPerformed
         gest_Personne b=new gest_Personne();
        b.setVisible(true);
        fermer();
    }//GEN-LAST:event_retourbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_benevole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_benevole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_benevole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_benevole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_benevole().setVisible(true);
            }
        });
    }
 public void tablelord(){
          
    try{
    String sql="SELECT `idPersonne`, `nom`, `prenom`, `dateNaissance`, `email`, `password`, `dateEntree`, `dateSortie`, `dateInscription` FROM `personne` WHERE groupe='B';";
    pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
    
   
    TableDoc.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
    }
       catch(Exception e){JOptionPane.showConfirmDialog(rootPane, e);}}
  
  public void clock(){
        {
            Thread clock=new Thread(){
            public void run(){
            try{
            while(true)
            {Calendar cal= new GregorianCalendar();
            int day=cal.get(Calendar.DAY_OF_MONTH);
            int month=cal.get(Calendar.MONTH)+1;
            int year=cal.get(Calendar.YEAR);
            
            int second=cal.get(Calendar.SECOND);
            int minute =cal.get(Calendar.MINUTE);
            int hour =cal.get(Calendar.HOUR);
            
            bTime.setText(hour+":"+minute+":"+second);
            bDate.setText(year+"-"+month+"-"+day);
                 sleep(1000);
                    
            }}
            catch(Exception e){JOptionPane.showMessageDialog(rootPane,e);}}
        };
        clock.start();}}
    
    
    
       private void clearFiled(){
        
        
       IdField.setText("");   
    NomField.setText(""); 
    PrenomFieled.setText(""); 
    dateTextField.setText("");    
    jPasswordField1.setText(""); 
    EmailField.setText(""); 
    dateentreeField.setText(""); 
    datesortieField.setText("");      
    dateinscField.setText("");
    
    jPasswordField1.setText(""); 
    
    }
    
    private void autoId(){
       try {
         String sql="SELECT `idPersonne` from `personne`order by idPersonne desc limit 17";
         pst = conn.prepareStatement(sql);
         rs=pst.executeQuery();
         if(rs.next()){
         String rnno=rs.getString("idPersonne");
         int co=rnno.length();
         String txt=rnno.substring(0,2);
         String num=rnno.substring(2,co);
         int n = Integer.parseInt(num);
         n++;
         String snum=Integer.toString(n);
         String ftxt=txt+snum;
         IdField.setText(ftxt);}
         else{
         IdField.setText("MYS0000");}
       
       }catch(Exception e){}}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterButton;
    private javax.swing.JLabel DateEntreeLabel;
    private javax.swing.JLabel DateInsLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel DateSortieLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField IdField;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JButton ModifierButton;
    private javax.swing.JTextField NomField;
    private javax.swing.JLabel NomLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PrenomFieled;
    private javax.swing.JLabel PrenomLabel;
    private javax.swing.JButton SupprimerButton;
    private javax.swing.JTable TableDoc;
    private javax.swing.JLabel bDate;
    private javax.swing.JLabel bTime;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField dateentreeField;
    private javax.swing.JTextField dateinscField;
    private javax.swing.JTextField datesortieField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton retourbutton;
    // End of variables declaration//GEN-END:variables
}
