/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mediatheque1;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Gestion_ecran extends javax.swing.JFrame {

    Connection con= null;
    PreparedStatement pst= null;
    PreparedStatement ps= null;
    ResultSet rs= null;
    public Gestion_ecran() {
        initComponents();
         clock();
        con = Connectionbdd.ConnecrDb();
    }
public void fermer(){dispose();}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bDate = new javax.swing.JLabel();
        bTime = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AjouterEcran = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CodeEcran_text = new javax.swing.JTextField();
        Disponible_text = new javax.swing.JTextField();
        EnService_text = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        EnService = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CodeEcran_text4 = new javax.swing.JTextField();
        EnService_text3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        Disponibilité = new javax.swing.JPanel();
        c = new javax.swing.JTextField();
        Disponible_text1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 50));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel4.setText("MYS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 60));

        bDate.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bDate.setText("Date");
        jPanel1.add(bDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 190, 30));

        bTime.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bTime.setText("Time");
        jPanel1.add(bTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 200, -1));

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 153));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        AjouterEcran.setBackground(new java.awt.Color(0, 153, 153));
        AjouterEcran.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                AjouterEcranComponentAdded(evt);
            }
        });
        AjouterEcran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Code Ecran:");
        AjouterEcran.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Disponibilité :");
        AjouterEcran.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 160, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("En service :");
        AjouterEcran.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));
        AjouterEcran.add(CodeEcran_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 260, 30));
        AjouterEcran.add(Disponible_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 260, 30));

        EnService_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnService_textActionPerformed(evt);
            }
        });
        AjouterEcran.add(EnService_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 260, 30));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add2.png"))); // NOI18N
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        AjouterEcran.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 230, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionec.png"))); // NOI18N
        AjouterEcran.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 26, 190, 150));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        AjouterEcran.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 170, 50));

        jLabel7.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ajouter Ecran");
        AjouterEcran.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 26, 350, 40));

        jTabbedPane1.addTab("Ajouter Ecran", AjouterEcran);

        EnService.setBackground(new java.awt.Color(0, 153, 153));
        EnService.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Sitka Heading", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ecran en service");
        EnService.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 430, 60));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Code Ecran:");
        EnService.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 140, 30));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("En service :");
        EnService.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 160, -1));

        CodeEcran_text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeEcran_text4ActionPerformed(evt);
            }
        });
        EnService.add(CodeEcran_text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 260, 30));
        EnService.add(EnService_text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 260, 30));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        jButton3.setText("Changer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        EnService.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 230, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecservice.png"))); // NOI18N
        EnService.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 26, 190, 150));

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        jButton7.setText("Retour");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        EnService.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 170, 50));

        jTabbedPane1.addTab("En Service", EnService);

        Disponibilité.setBackground(new java.awt.Color(0, 102, 102));
        Disponibilité.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        Disponibilité.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 280, 30));

        Disponible_text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Disponible_text1ActionPerformed(evt);
            }
        });
        Disponibilité.add(Disponible_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 280, 30));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Code Ecran :");
        Disponibilité.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 150, -1, 40));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Diponibilté :");
        Disponibilité.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 170, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diponibilité.png"))); // NOI18N
        Disponibilité.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 210, 180));

        jButton8.setBackground(new java.awt.Color(0, 102, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        jButton8.setText("Retour");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Disponibilité.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 170, 50));

        jLabel20.setFont(new java.awt.Font("Sitka Heading", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Disponibilité d'Ecran");
        Disponibilité.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 500, 60));

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        jButton4.setText("Changer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Disponibilité.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 230, 50));

        jTabbedPane1.addTab("Disponibilité", Disponibilité);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 970, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
           String sql = "insert into ecran (idEcran,disponible,enService)values(?,?,?)";
           pst = con.prepareStatement(sql);
           pst.setString(1,CodeEcran_text.getText());
           pst.setString(2,Disponible_text.getText());
           pst.setString(3,EnService_text.getText());
           pst.executeUpdate();
           
           JOptionPane.showMessageDialog(null,"enregistrement reussi");
        }catch(Exception e){
            e.printStackTrace();}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Personnel bn=new Personnel();
        bn.setVisible(true);
        fermer();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AjouterEcranComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_AjouterEcranComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_AjouterEcranComponentAdded

    private void CodeEcran_text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeEcran_text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeEcran_text4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  try{
            String sql = "UPDATE ecran SET enService=? where idEcran=?  ";
           
            pst = con.prepareStatement(sql);
           
           pst.setString(1,EnService_text3.getText());
           pst.setString(2,CodeEcran_text4.getText());
         
           pst.executeUpdate();
           
           
           JOptionPane.showMessageDialog(null,"modification valide");
           
        }catch(Exception e){
             e.printStackTrace();
             JOptionPane.showMessageDialog(null,e);
        }    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Personnel bn=new Personnel();
        bn.setVisible(true);
        fermer();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void Disponible_text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Disponible_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Disponible_text1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Personnel bn=new Personnel();
        bn.setVisible(true);
        fermer();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            try{
            String sql = "UPDATE ecran SET disponible=? where idEcran=?  ";
           
            pst = con.prepareStatement(sql);
           
           pst.setString(1,c.getText());
           pst.setString(2,Disponible_text1.getText());
         
           pst.executeUpdate();
           
           
           JOptionPane.showMessageDialog(null,"modification valide");
           
        }catch(Exception e){
             e.printStackTrace();
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void EnService_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnService_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnService_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_ecran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_ecran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_ecran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_ecran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_ecran().setVisible(true);
            }
        });
    }
public void clock(){
        {
            Thread clock=new Thread(){
            public void run(){
            try{
            while(true)
            {Calendar cal= new GregorianCalendar();
            int day=cal.get(Calendar.DAY_OF_MONTH);
            int month=cal.get(Calendar.MONTH)+1;
            int year=cal.get(Calendar.YEAR);
            
            int second=cal.get(Calendar.SECOND);
            int minute =cal.get(Calendar.MINUTE);
            int hour =cal.get(Calendar.HOUR);
            
            bTime.setText(hour+":"+minute+":"+second);
            bDate.setText(year+"-"+month+"-"+day);
                 sleep(1000);
                    
            }}
            catch(Exception e){JOptionPane.showMessageDialog(rootPane,e);}}
        };
        clock.start();}}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AjouterEcran;
    private javax.swing.JTextField CodeEcran_text;
    private javax.swing.JTextField CodeEcran_text4;
    private javax.swing.JPanel Disponibilité;
    private javax.swing.JTextField Disponible_text;
    private javax.swing.JTextField Disponible_text1;
    private javax.swing.JPanel EnService;
    private javax.swing.JTextField EnService_text;
    private javax.swing.JTextField EnService_text3;
    private javax.swing.JLabel bDate;
    private javax.swing.JLabel bTime;
    private javax.swing.JTextField c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
