/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package mediatheque1;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static mediatheque1.Emprenter_doc.groupe;

/**
 *
 * @author PC
 */
public class profil_user extends javax.swing.JInternalFrame {

    Connection con= null;
    PreparedStatement pst= null;
    ResultSet rs= null;
  DefaultTableModel model;
  static String email;
  static String password;
    public profil_user(String email,String password) {
        this.email=email;
        this.password=password;
        initComponents();
        con=Connectionbdd.ConnecrDb();
        affiche();
    }
    void fermer(){dispose();}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IdLecteur_text = new javax.swing.JTextField();
        Cotisaion_text = new javax.swing.JTextField();
        Nom_text = new javax.swing.JTextField();
        Prenom_text = new javax.swing.JTextField();
        Email_text = new javax.swing.JTextField();
        DateNaissance_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id Lecteur :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, -1));

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prenom:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, -1));

        jLabel4.setBackground(new java.awt.Color(0, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 153, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date de naissance:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 153, 153));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cotisation:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        IdLecteur_text.setEditable(false);
        IdLecteur_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdLecteur_textActionPerformed(evt);
            }
        });
        jPanel2.add(IdLecteur_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 122, 180, 30));

        Cotisaion_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cotisaion_textActionPerformed(evt);
            }
        });
        jPanel2.add(Cotisaion_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 180, 30));
        jPanel2.add(Nom_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 180, 30));

        Prenom_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prenom_textActionPerformed(evt);
            }
        });
        jPanel2.add(Prenom_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 180, 30));

        Email_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_textActionPerformed(evt);
            }
        });
        jPanel2.add(Email_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 180, 30));

        DateNaissance_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateNaissance_textActionPerformed(evt);
            }
        });
        jPanel2.add(DateNaissance_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 180, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdLecteur_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdLecteur_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdLecteur_textActionPerformed

    private void Cotisaion_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cotisaion_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cotisaion_textActionPerformed

    private void Prenom_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prenom_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Prenom_textActionPerformed

    private void Email_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_textActionPerformed

    private void DateNaissance_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateNaissance_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateNaissance_textActionPerformed
    
          
          public void affiche(){
              try{
              String sql= "select * from personne where email= ? and password=? " ;
              pst = con.prepareStatement(sql);
              pst.setString(1, email);
               pst.setString(2, password);
              rs = pst.executeQuery();
              if(rs.next())
              {
                  String id = rs.getString("idPersonne");
                   String nom= rs.getString("nom");
                   String prenom = rs.getString("prenom");
                   String e =rs.getString("email");
                   String DateNaissance = rs.getString("dateNaissance");
                   String cot =rs.getString("cotisation");
              //String pass1= pass.substring(0,3);

              
              IdLecteur_text.setText(id);
              Nom_text.setText(nom);
              Prenom_text.setText(prenom);
              Email_text.setText(e);
              DateNaissance_text.setText(DateNaissance);
              Cotisaion_text.setText(cot);
              }

          }catch(Exception e){
              e.printStackTrace();
          } 

          }
      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cotisaion_text;
    private javax.swing.JTextField DateNaissance_text;
    private javax.swing.JTextField Email_text;
    private javax.swing.JTextField IdLecteur_text;
    private javax.swing.JTextField Nom_text;
    private javax.swing.JTextField Prenom_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
